### PR TITLE
Fix using deprecated evil-redirect-digit-argument

### LINKED ISSUE #36: evil-redirect-digit-argument was removed
`evil-redirect-digit-argument` was [removed](https://github.com/emacs-evil/evil/commit/17c635f6e1f538bf4b2c3c276ddd9d4d165a52fb#diff-47302cddd5e39bfe2c8dcd1b006b8a2c683f070472d9bb138d20a243a3d71aa1L745) from `evil-maps.el` rendering errors when using spacemacs.

```
File mode specification error: (void-function evil-redirect-digit-argument)
```

I don't understand your code enough to provide PR, but at least this PR for evil-org-mode might be helpfull https://github.com/Somelauw/evil-org-mode/pull/95

### PR DESCRIPTION
**Pull request by kassick**
Fixes https://github.com/syl20bnr/evil-iedit-state/issues/36

### CODE REVIEW

**Comment by eauc** [comment]
thanks, this fix works for me too :wave:

**Review by bhipple — APPROVED** [review]

**Comment by j-martin** [comment]
@syl20bnr serait-il possible de merger ce PR(un seul mot de changé)

**Comment by tgroshon** [comment]
This is GREAT!  Fixed the problem for me.  Looking forward to this getting merged :)

**Comment by phenix-factory** [comment]
I can confirm that this fix iedit mode for me.

**Comment by bhoudebert** [comment]
Working as well thanks mate!

**Review by lebensterben — APPROVED** [review]
LGTM

**Review by br3athein — APPROVED** [review]

**Comment by syl20bnr** [comment]
Thank you! Sorry for the long delay. Will release a new version today.

**Comment by syl20bnr** [comment]
1.3 should be available shortly on NonGNU ELPA and MELPA.

**Pull request merged**
